version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies

- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies

- package-ecosystem: gradle
  directory: "/app"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies

- package-ecosystem: gradle
  directory: "/common"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies

- package-ecosystem: gradle
  directory: "/libraries/parcelable"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
  
- package-ecosystem: gradle
  directory: "/tasker-plugin"
  schedule:
    interval: weekly
    day: "saturday"
    time: '04:00'
  open-pull-requests-limit: 10
  reviewers:
  - rm3l
  labels:
  - dependencies
