stages:
  - build

################################################################################
# Build
################################################################################
build_project:
  image: registry.gitlab.com/lemra/router-companion-android/android-sdk:latest
  stage: build
  before_script:
    - chmod +x ./gradlew

  # Note on caching: 
  # We should not rely upon the cache, as it is done on a best effort basis, 
  # i.e., no cache if run on different runners
  cache:
    key: "cache-$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG" # per branch caching
    untracked: true
    paths:
      - $GRADLE_USER_HOME/caches/
      - $GRADLE_USER_HOME/wrapper/
      - $GRADLE_USER_HOME/build-cache/

  script:
    - ./gradlew :app:assembleDevDebug :tasker-plugin:assembleDevDebug testGoogleDebugUnitTest htmlDependencyReport

  artifacts:
    when: always
    paths:
    - app/build/reports
    - app/build/outputs/
    - app/build/doc

    - common/build/reports
    - common/build/outputs

    - tasker-plugin/build/outputs
    - tasker-plugin/build/reports
