stages:
  - build
  - deploy

# This is NOT a job and will be ignored by GitLab-CI
.deploy_stage_operation_key: &deploy_stage_operation  # This is an anchor
  before_script:
    - apk update || apt-get update -y

    # For CD pipeline
    # Install ssh-agent if not already installed, it is required by Docker.
    # (change apt-get to yum if you use a CentOS-based image)
    - 'which ssh-agent || apk add openssh || apt-get install openssh-client -y'

    # Run ssh-agent (inside the build environment)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -

    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

    # For Docker builds disable host key checking. Be aware that by adding that
    # you are suspectible to man-in-the-middle attacks.
    # WARNING: Use this only with the Docker executor, if you use it with shell
    # you will overwrite your user's SSH config.
    # - mkdir -p ~/.ssh
    # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # In order to properly check the server's host key, assuming you created the
    # SSH_SERVER_HOSTKEYS variable previously, uncomment the following two lines
    # instead.
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'

    - 'which rsync || apk add rsync || apt-get install rsync -y'
  # after_script:
  #   - echo after script



build:
  image: registry.gitlab.com/lemra/router-companion-android:latest
  stage: build
  script:
    - ./gradlew htmlDependencyReport :app:assembleAmazonDebug :tasker-plugin:assembleAmazonDebug
  artifacts:
    paths:
    - app/build/reports   
    - app/build/outputs/
    - app/build/doc
    - common/build/reports
    - common/build/outputs
    - tasker-plugin/build/outputs
    - tasker-plugin/build/reports

production_messaging:
  <<: *deploy_stage_operation  # This is a reference to the anchor.
  image: alpine:3.6
  stage: deploy
  script:
    - ssh -p 1022 ci@rm3l.org "mkdir -p /home/ci/router-companion-android"
    - rsync -ravz -e 'ssh -p 1022' --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='.gradle' --exclude='build' --delete-excluded ./messaging ci@rm3l.org:/home/ci/router-companion-android
    - ssh -p 1022 ci@rm3l.org "cd /home/ci/router-companion-android/messaging && docker-compose -p router-companion-android-messaging up -d --build"
  only:
    - master
  environment: production

production_tools:
  <<: *deploy_stage_operation  # This is a reference to the anchor.
  image: alpine:3.6
  stage: deploy
  script:
    - ssh -p 1022 ci@rm3l.org "mkdir -p /home/ci/router-companion-android"
    - rsync -ravz -e 'ssh -p 1022' --exclude='.git/' --exclude='.gitlab-ci.yml' --exclude='.gradle' --exclude='build' --delete-excluded ./tools ci@rm3l.org:/home/ci/router-companion-android
    - ssh -p 1022 ci@rm3l.org "cd /home/ci/router-companion-android/tools && docker-compose -p router-companion-android-tools up -d --build"
  only:
    - master
  environment: production
