#
# Extra-services, deployed to tools.rm3l.org
#

version: '3.3'

services:
  #
  # MAC OUI
  #
  mac-oui:
    image: klauspost/oui
    ports:
      - "5000:5000"
    labels:
      org.rm3l.router_companion.service_name: "mac-oui"
      org.rm3l.router_companion.service_description: "Microservice for looking up manufacturers from MAC addresses"
      org.rm3l.router_companion.service_url: "http://tools.rm3l.org:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/fc:aa:14"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always
    #   resources:
    #     limits:
    #       cpus: '0.001'
    #       memory: 50M

  #
  # GeoIP Lookup
  #
  geoip:
    image: fiorix/freegeoip
    ports:
      - "5080:8080"
    labels:
      org.rm3l.router_companion.service_name: "geoip"
      org.rm3l.router_companion.service_description: "IP geolocation web server"
      org.rm3l.router_companion.service_url: "http://tools.rm3l.org:5080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/json/8.8.8.8"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always
    
