# Build
name: Build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          # Only write to the cache for builds on the 'main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          arguments: --info testGoogleDebugUnitTest

  reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          # Only write to the cache for builds on the 'main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          arguments: --info htmlDependencyReport

  assemble:
    strategy:
      fail-fast: false
      matrix:
        app: [ app, tasker-plugin ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Assemble ${{ matrix.app }}
        # TODO Split this in different Gradle executions
        uses: gradle/gradle-build-action@v2
        with:
          # Only write to the cache for builds on the 'main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          arguments: --info :${{ matrix.app }}:assembleDevDebug
