# Build
name: Build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Assemble
        # TODO Split this job
        run: |
          ./gradlew \
            --info \
            :app:assembleDevDebug \
            :tasker-plugin:assembleDevDebug \
            testGoogleDebugUnitTest \
            htmlDependencyReport
