name: Lint
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  tags:
  - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Spotless
        run: ./gradlew spotlessCheck
